### ISSUE TITLE
Fehler beim Export

### ISSUE THREAD

**Issue by aljoshakoecher** [HamiedNabizada/FPB.JS#1]
In der Demo-App lässt sich das Minimal-Beispiel (Systemgrenze, Input, Output, Prozess) nicht exportieren. Beim Versuch, das als Datei zu exportieren, gibt's folgenden Fehler in der Konsole:
`Uncaught ReferenceError: FPBJson is not defined`

Um den Fehler nachzuvollziehen, einfach das kleinstmögliche Beispiel bauen und alles (alle Elemente inklusive grafischer Infos) als Datei exportieren.

**Comment by HamiedNabizada** [comment]
Hi, hatte versehentlich noch einen Testcode für die bald erscheinende Importierfunktion hinterlegt gehabt, der den Fehler verursachte. 
Ist jetzt aber gefixt: https://github.com/HamiedNabizada/FPB.JS/commit/73c23e2e8987218afb744588b85d76c9d348bb30
vielen Dank!
