### ISSUE TITLE
"Drag & Drop" bei Verbindern nicht mehr möglich

### ISSUE THREAD

**Issue by aljoshakoecher** [HamiedNabizada/FPB.JS#11]
Bis vor kurzem konnte man Elemente verbinden, indem man den Verbinder neben dem Objekt geklickt und auf das Zielelement gezogen hat. Das geht jetzt nicht mehr, die FpbContextPadProvider.js meldet "Cannot read property 'srcElement' of undefined".

**Comment by aljoshakoecher** [comment]
Das Problem ist hier: 
```javascript
function startConnect(event, element, autoActivate) {
    if (is(element, 'fpb:Object')) {
      let hint;
      let className;
      // Unterscheidung ob Verbindung über MouseClick oder Touch
      if (event.type == 'click') {
        className = event.srcElement.className;
      } else {
        className = event.srcEvent.srcElement.className;
      }
...
```

Genauer gesagt nach dem Kommentar. Wenn man den Verbinder ziehen will (wie oben beschrieben), wird ein "dragstart"-event ausgelöst. Man fällt also in den zweiten Fall. Das Event sieht aber aus wie ein "click"-event, es gibt kein srcEvent, das srcElement ist direkt ein Objekt innerhalb des "event".
Ist die Unterscheidung hier überhaupt nötig? Oder kann man nicht einfach das passende Event an diese Funktion übergeben? Um das beurteilen zu können, bin ich leider noch nicht genug "im Code drin" 😃 
Falls die Unterscheidung hier nötig ist, muss beim Click-Fall auch der dragstart-Fall enthalten sein.

**Comment by aljoshakoecher** [comment]
@HamiedNabizada Hätte nen Fix, den ich gerne (auf nen anderen Branch, dann PR) pushen würde. Darf ich leider nicht... 😢 Kannst du mich als Contributor hinzufügen?

**Comment by HamiedNabizada** [comment]
Die Information die aus dem Event extrahiert und in die Variable className hinterlegt wird, bestimmt welcher Verbindertyp (Flow, Alternative, Parallel) durch den Nutzer ausgewählt wurde. Durch https://github.com/HamiedNabizada/FPB.JS/issues/7 stellte sich heraus, dass durch dieses Vorgehen Probleme bei Touchdevices entstehen und deswegen wurde mit https://github.com/HamiedNabizada/FPB.JS/commit/1c91bef6b18e79808a72dfa0e6286f8778fba607 die Unterscheidung zwischen Click- und Touch-Events eingeführt. Also die Unterscheidung ist aktuell  notwendig, bin aber für jeden Änderung offen. :D 
Ich hab dir mal eine Einladung als Collaborator geschickt.

PS: In Diagram.JS bzw. BPMN.JS findet die Unterscheidung ausschließlich regelbasiert statt. Dort besteht somit nicht wirklich die Möglichkeit verschiedene Verbindertypen zwischen zwei Elementen auszuwählen.
