### ISSUE TITLE
Import .json mit "technical resource" fehlerhaft

### ISSUE THREAD

**Issue by JessGrantham** [HamiedNabizada/FPB.JS#13]
Der Export einer Grafik (Information Level: Total; Information: All processes; Download) funktioniert ohne angezeigte Fehler in der Konsole. Öffnet man die "Import"-Funktion, lädt eine zuvor exportierte .json-Datei, die eine technische Ressource enthält, und drückt dann auf "Import", erscheinen im Moment des Clickens folgende Fehlermeldungen:

![Screen1](https://user-images.githubusercontent.com/3308564/73246447-f2181180-41ae-11ea-8fa9-a0ff081b1e10.jpg)
![Screen2](https://user-images.githubusercontent.com/3308564/73246446-f17f7b00-41ae-11ea-8b4e-b21b7c100ee1.jpg)
![Screen3](https://user-images.githubusercontent.com/3308564/73246445-f17f7b00-41ae-11ea-9b3b-3ddb2ef5ab9f.jpg)
![Screen4](https://user-images.githubusercontent.com/3308564/73246444-f17f7b00-41ae-11ea-80d5-bca2c437493a.jpg)

[Console_output_1.log](https://github.com/HamiedNabizada/FPB.JS/files/4121304/Console_output_1.log)
[test.zip](https://github.com/HamiedNabizada/FPB.JS/files/4121308/test.zip)

Die Datei wird nicht importiert, auch schließt sich die "Import"-Maske nicht. 

Wird eine Datei ohne technische Ressource importiert, funktioniert alles und die Konsole zeigt keinen Fehler an.

(.log-Datei enthält Kopie des Konsolentextes, Screen1-4 Screenshots der Konsole, test.zip enthält test.json, welche importiert werden sollte)

**Comment by HamiedNabizada** [comment]
Hallo Jess,
vielen Dank für den Bug-Report. Es handelte sich um einen Logikfehler im Code:
- Usage-Connections, die ausgehend von einer TR zu einem Prozessoperator gezogen worden sind, wurden nicht korrekt gespeichert.
Dies wurde behoben mit:  https://github.com/HamiedNabizada/FPB.JS/commit/36f75368e20f7fd3fa827eb3423b90c2af6120a9

Sollte im Zusammenhang zu diesem Issue doch noch Probleme auftauchen, dann teile uns das bitte mit. Die Tests die ich dazu durchgeführt habe waren aber alle ok. 

Viele Grüße
