### ISSUE TITLE
"Import" Fehlerhaft

### ISSUE THREAD

**Issue by Paul193247** [HamiedNabizada/FPB.JS#16]
Eine Datei wurde Fehlerhaft gespeichert, sodass in mehreren Objekten mit dem type ""fpb:ParallelFlow" bei "inTandemWith" auf ein nicht vorhandenes Objekt referiert wird. Fehlermeldung: 
TypeError: Cannot read properties of undefined (reading 'businessObject')
    at JSONImporter.js:372:47
    at Array.forEach (<anonymous>)
    at xs.updateDepedencies (JSONImporter.js:365:49)
    at JSONImporter.js:53:30
    at Array.forEach (<anonymous>)
    at JSONImporter.js:52:39
    at Array.forEach (<anonymous>)
    at JSONImporter.js:27:29
    at EventBus.js:515:13
    at ze._invokeListener (EventBus.js:366:19)

Mögliche Lösung: 
FPB.JS\app\fpb\importer\JSONImporter.js:

Zeile 367 - 376: 

let partner = container.find((partner) => {
   if ([partner.id](http://partner.id/) === tandemFlow) {

        collectionRemove(partner.businessObject.inTandemWith, [element.id](http://element.id/));
        collectionAdd(partner.businessObject.inTandemWith, element.businessObject);
  }
 return [partner.id](http://partner.id/) === tandemFlow

 });

if (partner){
   let flow = partner.businessObject
   collectionRemove(element.businessObject.inTandemWith, [flow.id](http://flow.id/));
   collectionAdd(element.businessObject.inTandemWith, flow);
 }

statt:

let flow = container.find((partner) => {
    if ([partner.id](http://partner.id/) === tandemFlow) {
         collectionRemove(partner.businessObject.inTandemWith, [element.id](http://element.id/));
         collectionAdd(partner.businessObject.inTandemWith, element.businessObject);
   }
   return [partner.id](http://partner.id/) === tandemFlow

}).businessObject;
collectionRemove(element.businessObject.inTandemWith, [flow.id](http://flow.id/));
collectionAdd(element.businessObject.inTandemWith, flow);

FPB.JS\app\fpb\modeling\FpbLayouter.js:

Zeile 104:

if (is(connection, 'fpb:ParallelFlow') && connection.businessObject.inTandemWith[0] && connection.businessObject.inTandemWith[0].di) {

statt:

if (is(connection, 'fpb:ParallelFlow') && connection.businessObject.inTandemWith[0]) {

**Comment by HamiedNabizada** [comment]
Hi Paul,

vielen Dank! Ich habe deine Änderungsvorschlag übernommen und getestet. Der Import von JSON-Files mit fehlerhaften "inTandemWith" funktioniert jetzt :)  Tatsächlich wird bei einem anschließenden Export jedoch die fehlerhafte ID durch null ersetzt (und die richtige ID zusätzlich wieder hinzugefügt). Ich konnte noch nicht entdecken, ob das irgendwelche Auswirkungen hat, deshalb habe ich die Änderungen (noch) nicht auf demo.fpbjs.net deployed, sondern auf https://dev.fpbjs.net/

Falls dir also etwas auffallen sollte, lass es mich gerne wissen.


 Commit https://github.com/HamiedNabizada/FPB.JS/commit/053a0dee0369df92a5edd9861485d2fbdf4f8b36

**Comment by HamiedNabizada** [comment]
FYI: Zur Zeit ist die Domain down, da der Webhoster seinen Dienst eingestellt. Ich versuche zeitnah FPB.js auf einem neuen Anbieter zu deployen.
