### ISSUE TITLE
Speicherung der Verbundenheit in exportiertem .json

### ISSUE THREAD

**Issue by aljoshakoecher** [HamiedNabizada/FPB.JS#2]
Frage:
Müsste nicht in jeder exportierten .json die Verbundenheit der Elemente abgespeichert werden? Ein Flow sieht aktuell so aus:
`{
    "labels": [],
    "id": "a90f8803-bdc0-456a-8cfd-9cd673b34a0e",
    "type": "fpb:Flow",
    "waypoints": [
    {
        "original": {
	    "x": 672,
	    "y": 144
        },
        "x": 672,
	"y": 144
    },
    {
        "x": 672,
	"y": 215
    },
    ...
    ]
},
`

Da fehlt doch die Verknüpfung zu den Elementen, die über diesen Flow miteinander verknüpft sind, oder?

**Comment by HamiedNabizada** [comment]
Hi Aljosha,
die .json Datei trennt die grafischen Informationen zur Wiederherstellung des Prozessbildes von den logischen Dateninformationen.
Die exportierte JSON Datei hat je Prozessansicht ein eigenes Objekt, das wiederum bei totalem Export aus 3 Objekten besteht: "process", "elementDataInformation" und "elementVisualInformation".
- process gibt allgemeine Informationen über die Prozessansicht wieder
- elementDataInformation enthält je ein Objekt pro Element  in der Prozessansicht. Die Information wie eine Flussverbindung Elemente miteinander verknüpft, wird bei den Flow-Objekten hier mitgespeichert. Die IDs in den Einträgen sourceRef und targetRef sind die IDs, der Elemente, die die Flussverbindung miteinander verknüpft:
```json
            {
                "$type": "fpb:Flow",
                "id": "76ab2c81-f9e5-40f2-a098-e8058f7db7ee",
                "sourceRef": "0294d110-58dc-4def-8e21-74ee3a33f8f2",
                "targetRef": "bac302d9-7cd1-43b1-8a38-5636214eec9d"
            },
```
Zusätzlich verweist das Element, von dem eine Verbindung ab oder eingeht, auf die entsprechende FlowID. In dem Beispiel geht der obige Flow aus dem Product ab:
```json
            {
                "$type": "fpb:Product",
                "id": "0294d110-58dc-4def-8e21-74ee3a33f8f2",
                "identification": {
                    "$type": "fpb:Identification",
                    "uniqueIdent": "0294d110-58dc-4def-8e21-74ee3a33f8f2",
                    "longName": "",
                    "shortName": "",
                    "versionNumber": "",
                    "revisionNumber": ""
                },
                "isAssignedTo": [
                    "bac302d9-7cd1-43b1-8a38-5636214eec9d"
                ],
                "incoming": [],
                "outgoing": [
                    "76ab2c81-f9e5-40f2-a098-e8058f7db7ee"
                ]
            }

```

- in elementVisualInformation sind lediglich Positionierungsinformationen hinterlegt. Diese werden nur benötigt, wenn eine exportierte json zu einem späteren Zeitpunkt in FPB.JS weiterbearbeitet werden soll:
```json
            {
                "id": "76ab2c81-f9e5-40f2-a098-e8058f7db7ee",
                "type": "fpb:Flow",
                "waypoints": [
                    {
                        "original": {
                            "x": 493,
                            "y": 93
                        },
                        "x": 493,
                        "y": 93
                    },
                    {
                        "x": 493,
                        "y": 165
                    },
                    {
                        "x": 450,
                        "y": 165
                    },
                    {
                        "original": {
                            "x": 450,
                            "y": 236
                        },
                        "x": 450,
                        "y": 236
                    }
                ]
            }
```

In den nächsten Tagen folgt aber noch eine ausführliche Dokumentation über das Datenmodell von FPB.JS.

**Comment by aljoshakoecher** [comment]
Okay, so hab ich es auch erwartet. Gestern hatte ich auch einen kompletten Export gemacht, hatte aber nur die grafischen Infos... Vielleicht hing das mit dem anderen Issue (#1) zusammen? 
Kannst den hier auch gerne schließen, so sieht's ja gut aus 👍
