### ISSUE TITLE
Fehler beim Dekomponieren

### ISSUE THREAD

**Issue by HSU-Max** [HamiedNabizada/FPB.JS#4]
Nach Anlegen einer Systemgrenze mit Produkten, Energien, Informationen usw. habe ich dekomponiert und dort Sachen hinzugefügt. Gehe ich nun auf die höhere Systemebene verschwinden die Eingänge (Produkte, Energien, Informationen)

**Comment by HamiedNabizada** [comment]
Hi, danke für den Hinweis. 
Leider kann ich den Fehler nicht reproduzieren. Bei mir erscheinen im beschriebenen Szenario keine Auffälligkeiten. Könntest du dazu noch ein paar mehr Details liefern, wie dies zustande gekommen ist?

Mit ist allerdings bekannt, dass Relationen von In- und Outputs auf der Systemgrenze in der dekomponierten Ansicht gelöscht werden, wenn im übergeordneten Prozess die Relation zum entsprechenden Prozessoperator gelöscht und dann wieder hinzugefügt wird.
Das passiert auch, wenn eine normale Flussverbindung zu einem bereits dekomponierten Prozessoperator im nachhinein zu einem parallelen bzw. alternativen Fluss transformiert wird und vice versa. Die Verbindungen von den entsprechenden Flussverbindungen in der dekomponierten Sicht werden in dem Fall dann gelöscht. Das ist ein ungewünschtes Verhalten, woran ich derzeit noch an einer Lösung arbeite.

**Comment by HSU-Max** [comment]
Hi Hamied,

 

das ist das Problem gewesen. J Dann viel Spaß bei Lösen und Danke!

 

Viele Grüße,

Max

 

Von: Hamied Nabizada <notifications@github.com> 
Gesendet: Mittwoch, 27. November 2019 14:13
An: HamiedNabizada/FPB.JS <FPB.JS@noreply.github.com>
Cc: HSU-Max <maximilian.rappl@hsu-hh.de>; Author <author@noreply.github.com>
Betreff: Re: [HamiedNabizada/FPB.JS] Fehler beim Dekomponieren (#4)

 

Hi, danke für den Hinweis.
Leider kann ich den Fehler nicht reproduzieren. Bei mir erscheinen im beschriebenen Szenario keine Auffälligkeiten. Könntest du dazu noch ein paar mehr Details liefern, wie dies zustande gekommen ist?

Mit ist allerdings bekannt, dass Relationen von In- und Outputs auf der Systemgrenze in der dekomponierten Ansicht gelöscht werden, wenn im übergeordneten Prozess die Relation zum entsprechenden Prozessoperator gelöscht und dann wieder hinzugefügt wird.
Das passiert auch, wenn eine normale Flussverbindung zu einem bereits dekomponierten Prozessoperator im nachhinein zu einem parallelen bzw. alternativen Fluss transformiert wird und vice versa. Die Verbindungen von den entsprechenden Flussverbindungen in der dekomponierten Sicht werden in dem Fall dann gelöscht. Das ist ein ungewünschtes Verhalten, woran ich derzeit noch an einer Lösung arbeite.
