### ISSUE TITLE
Nutzen von Verbindern mit "Touch Devices"

### ISSUE THREAD

**Issue by aljoshakoecher** [HamiedNabizada/FPB.JS#7]
Die einzelnen Elemente lassen sich zwar problemlos anlegen, aktuell kann man aber Verbinder auf Touch Devices wie Smartphones oder Tablets nicht nutzen. Es wirkt so, als ob das Klick-Event "blockiert" bzw. noch beim Quell-Element oder dem Verbinder "hängt", wenn man das Ziel-Element anklicken will.

Es wäre cool, wenn man fpb.js zukünftig auch auf Tablets nutzen könnte.

**Comment by HamiedNabizada** [comment]
Funktioniert jetzt mit:  https://github.com/HamiedNabizada/FPB.JS/commit/1c91bef6b18e79808a72dfa0e6286f8778fba607
