### ISSUE TITLE
Unterscheidung zwischen alternativen und parallelen Inputs

### ISSUE THREAD

**Issue by aljoshakoecher** [HamiedNabizada/FPB.JS#8]
Aktuell bekommt man keine Auswahl zwischen parallelen und alternativen Flows, wenn man Input-Elemente mit einem Prozessoperator anlegen will, s. folgenden Screenshot:

![image](https://user-images.githubusercontent.com/50097079/70610336-b1b30300-1c03-11ea-85c7-25bebf31c7e0.png)

Diese Auswahlmöglichkeit braucht man aber, um klarzumachen, ob die beiden Produkte alternativ oder parallel in den Prozess eingehen. Hier jeweils ein Beispiel für die beiden Möglichkeiten:

![image](https://user-images.githubusercontent.com/50097079/70610512-fdfe4300-1c03-11ea-98ea-7571b5853135.png)

**Comment by HamiedNabizada** [comment]
https://github.com/HamiedNabizada/FPB.JS/commit/1c91bef6b18e79808a72dfa0e6286f8778fba607
